retriever:
  file: "retreiver/report.pdf"
  headers_to_split_on:
    - ["#", "Header 1"]
    - ["##", "Header 2"]
  load_documents: false
  collection_name: rag-chroma-report
  directory: vector_db
  top_k: 3
  top_k_compression: 3
  ensemble_weights: [0.3, 0.3, 0.4]
  cohere_rerank_model: rerank-english-v3.0

llm:
  gpt_5_mini: gpt-4o-mini
  temperature: 0
